name: Build Android & iOS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Android
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install Cordova
        run: npm install -g cordova
        
      - name: Install Cordova Resources Plugin
        run: sudo npm install -g --unsafe-perm cordova-res
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Cordova - Platform Add Android
        run: cordova platform add android
          
      - name: Cordova - Generate Resources
        run: cordova-res android
        
      - name: Cordova - Build Android
        run: cordova build android